### ISSUE TITLE
Frontend Task

### ISSUE THREAD

**Issue by shuzootani** [shuzootani/eating-for-me#1]
## Design touch up
dribbble
yummly
yelp

## Todo
- [x] image upload to firebase.storage and get progressive image if possible 
- [ ] grid layout and flex for fallback
- [x] place proper icons
- [ ] responsive layout using media-query
- [ ] fix as much performance issues as possible
- [ ] map in detail page(google map link)
- [x] map cluster in search result(sync cluster map and search result event)
[Map Cluster](https://tomchentw.github.io/react-google-maps/#markerclusterer)
- [x] fetch within geo location
https://github.com/firebase/geofire-js/issues/163
https://qiita.com/yabooun/items/da59e47d61ddff141f0c
https://stackoverflow.com/questions/36705355/finding-geohashes-of-certain-length-within-radius-from-a-point
http://janmatuschek.de/LatitudeLongitudeBoundingCoordinates#Longitude
https://angularfirebase.com/lessons/geolocation-query-in-firestore-realtime/
- [x] filter by tags(do it on client side)
- [x] sort by the number of matching tags(do it on client side)
- [x] load more && pagination
- [ ] call to action for those who want to get started their business.
- [ ] realtime open status comparing new Date() to business hours
- [x] draggable location adjustment
- [x] auto suggest for address inputs by geocoding location
- [ ] make everything work for mobile as well(onKeyDown ≠ onTap, responsive, menu)
- [ ] settings page(email update, password update)
- [ ] forgot password
- [x] isPublic toggle on manage page
- [x] professional type, professional list
- [ ] nice loading state(login, signup, fetch, image, anything-lazy)

## Other
- terms and privacy policy
- other pages(company, faq, help)
