### ISSUE TITLE
DEV: TODO

### ISSUE THREAD

**Issue by shuzootani** [shuzootani/eating-for-me#23]
- [x] add professionals array data in user object
- [x] fix category tab for mobile
- [x] geocoding from address that user inputs to geocode for map
- [x] finish up survey modal and apply them to search result
- [ ] limit the number of tags that business can select so that we don't allow them to select all tags.
- [x] make auto suggestions work as expected
- [ ] make loading page looks cool
- [x] revise image uploading process
- [ ] add meta tags and SEO stuff dynamically
